### ISSUE TITLE
Consider moving master > main for your repos

### ISSUE THREAD

**Issue by FloorD** [OfferZen-Make/plant_tech_ams#54]
I'd love to suggest to change from master to main for the default branch of your projects. That would involve changing existing public repositories, and possibly changing templates to use main when creating a new repository.

GitHub and GitLab changed to use main, and many organisations and communities followed suit. A bit of background on the master > main discussion: https://sfconservancy.org/news/2020/jun/23/gitbranchname/

And practical implementation: https://github.com/github/renaming

❤️

**Comment by pbrizzolari** [comment]
I hadn't really thought about it since the initial announcement by github but I have no problem with changing it. Let me take a look at it this weekend and I'll confirm when it's done.

**Comment by pbrizzolari** [comment]
I couldn't do it myself but Ben kindly handled it. Thanks Floor.
