### ISSUE TITLE
Can "the big picture" be updated to show which wire to connect the water pump to?

### ISSUE THREAD

**Issue by mvcds** [OfferZen-Make/plant_tech_ams#6]
Hello,

The water pump has two wires, one positive and one negative. The image "the big picture" shows that the transistor connects to the pump but it's not clear if the transistor or the ESP8266 goes to the positive port, at least not for a noob XD

So I'd suggest just to place a signal in "the big picture" saying + or - besides the water pump wires, just to be clear. Meanwhile, I am googling if there's a default for "negative go to ground port" and such.

(It seems the ground is negative but I am nor sure, tho I am proceeding anyway)

Thanks!

**Comment by benblaine** [comment]
@pbrizzolari can you share the updated pic?

**Comment by pbrizzolari** [comment]
@benblaine I'm trying to find a way of adding a note to the image in Fritzing, but it's really a terrible piece of software. It may actually be easier to just edit the exported image to include the + and - symbols.

**Comment by benblaine** [comment]
last I checked I resolved this :)
